import { env } from '../config/env';

console.log(`OPENCLAW_CONNECTOR_TOKEN=${env.OPENCLAW_CONNECTOR_TOKEN}`);
console.log(`OPENCLAW_CONNECTOR_TOKEN_FILE=${env.OPENCLAW_CONNECTOR_TOKEN_FILE}`);
console.log(`OPENCLAW_CONNECTOR_TOKEN_SOURCE=${env.OPENCLAW_CONNECTOR_TOKEN_SOURCE}`);
